---
title: "Testing Package Using Damgo"
output: html_document
---

```{r}
library("Rcpp")
library("tidyverse")
library("devtools")
library("brms")
library("rstan")
library("rstantools")
library("tidybayes")
library("ggplot2")
library("readxl")
```

```{r}
load_all()
```

```{r}
library("readxl")
xl_damgo_dr <- "C:/Users/marti/Downloads/damgo_dr_reformatted.xlsx"

damgo <- read_excel(xl_damgo_dr)

damgo
```

```{r}
ggplot2::ggplot(damgo) +
  ggplot2::geom_point(
    ggplot2::aes(x = log_dose,
        y = response),
    size = 1.0,
    color = "black") +
  ggplot2::labs(title = "Dose Response",
       x = "Log Dose",
       y = "Response")
```

```{r}
damgo_inits <- dr_inits(agonist = FALSE)
damgo_inits
```

```{r}
damgo_priors <- dr_priors(hill = brms::prior(normal(-1,1),ub = 0.1, nlpar = "hill"),
                          agonist = FALSE, 
                          top = 100)
damgo_priors
```

```{r}
sampling_priors <- dose_response_model(damgo, 
                                       "response",
                                       "log_dose",
                                       sigmoid_formula = no_predictors_dr_formula(),
                                       priors = damgo_priors,
                                       inits = damgo_inits,
                                       sample_prior = "only"
                                       )
sampling_priors
```

```{r}
plot_pp_check(sampling_priors, n = 50) + 
  ggplot2::xlim(-200,200) +
  ggplot2::ylim(0, 0.1)
```

```{r}
prior_densities(sampling_priors)
```

```{r}

damgo_model <- dose_response_model(damgo, 
                                   "response", 
                                   "log_dose",
                                   sigmoid_formula = no_predictors_dr_formula(),
                                   priors = damgo_priors,
                                   inits = damgo_inits)

damgo_model
```

```{r}
BayesPharma::traceplot(damgo_model)
```

```{r}
plot_pp_check(damgo_model)
```

```{r}
prior_posterior_densities(damgo_model)
```

```{r}
posterior_densities(damgo_model)
```

```{r}
damgo_draws <- posterior_response_draws(damgo_model, 
                                        lower = -9, 
                                        upper = -3,
                                        predictor_name = "Damgo")

damgo_draw_means <- posterior_mean(damgo_model,
                                   lower = -9, 
                                   upper = -3,
                                   predictor_name = "Damgo")

plot_trajectories(damgo,
                  predictors_col_name = NULL,
                  damgo$response,
                  damgo_draws,
                  damgo_draws$Response,
                  damgo_draw_means)

```

```{r}

plot_draws_data(model = damgo_model,
                n = 100,
                lower = -9,
                upper = -3,
                predictor_name = "Damgo",
                data = damgo,
                predictors_col_name = NULL,
                measurement = damgo$response,
                draws,
                pred_response,
                mean_draws,
                title = NULL,
                xlabel = "Log Dose",
                ylabel = "Response")
```

