---
title: "KOR antagonists"
output: html_document
---


```{r}
library("Rcpp")
library("tidyverse")
library("devtools")
library("brms")
library("rstan")
library("rstantools")
library("tidybayes")
library("ggplot2")
library("readxl")
library("bayesplot")

```

---
Load data
```{r}
xl_kor_antag_dr <- "C:/Users/marti/Downloads/kor_antag_dose_response_data.xlsx"

kor_antag <- read_excel(xl_kor_antag_dr)

kor_antag
```

```{r}
kor_sample_priors <- dose_response_model(kor_antag, 
                                         "normalized_measurement", 
                                         "log_dose", 
                                         "Drug",
                                         sigmoid_formula = predictors_dr_formula(),
                                         priors = dr_priors(agonist = FALSE, top = 100),
                                         inits = dr_inits(agonist = FALSE),
                                         sample_prior = "only")
kor_sample_priors
```

```{r}
BayesPharma::plot_pp_check(kor_sample_priors)  + 
  ggplot2::xlim(-200,200) +
  ggplot2::ylim(0, 0.01)
```

```{r}
prior_densities(kor_sample_priors)
```


```{r}
kor_model <- dose_response_model(kor_antag, 
                                 "normalized_measurement", 
                                 "log_dose", 
                                 "Drug",
                                 sigmoid_formula = predictors_dr_formula(),
                                 priors = dr_priors(agonist = FALSE, top = 100),
                                 inits = dr_inits(agonist = FALSE))

kor_model
```

```{r}
BayesPharma::traceplot(kor_model) 
```

```{r}
BayesPharma::plot_pp_check(kor_model,
                           "dens_overlay_grouped", 
                           group = 'predictors',
                           ndraws = 50)
```

```{r}
prior_posterior_densities(kor_model)
```

```{r}
posterior_densities(kor_model)
```

```{r}

kor_draws <- posterior_response_draws(kor_model)

kor_draw_means <- posterior_mean(kor_model)

plot_trajectories(kor_antag,
                  "Drug",
                  kor_antag$normalized_measurement,
                  kor_draws,
                  kor_draws$Response,
                  kor_draw_means)


```

```{r}
plot_draws_data(model = kor_model,
                n = 100,
                lower = -12,
                upper = -3,
                predictor_name = NULL,
                data = kor_antag,
                predictors_col_name = "Drug",
                measurement = kor_antag$normalized_measurement,
                draws,
                pred_response,
                mean_draws,
                title = NULL,
                xlabel = "Log Dose",
                ylabel = "Response")
```

