---
title: "Bayesian Sigmoid Model: Analysis of Four Kappa Opioid Receptor Antagonists"
author: "Madeline Martin"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bayesian Dose Response Modeling and Analysis of Four Kappa Opioid Receptor Antagonists}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r set-options}
#| echo=FALSE
options(rmarkdown.html_vignette.check_title = FALSE)

# inspired by https://www.jumpingrivers.com/blog/knitr-default-options-settings-hooks/
knitr::opts_chunk$set(
  cache = TRUE,
  echo = FALSE,
  fig.path = "sigmoid_model_KOR_antagonists/knitr-",
  fig.retina = 2, # Control using dpi
  fig.width = 6,  # generated images
  fig.height = 5, # generated images
  fig.pos = "t",  # pdf mode
  fig.align = "center",
  dpi = if (knitr::is_latex_output()) 72 else 300, 
  out.width = "100%")

set.seed(0)
```

```{r load-packages}
#| echo=FALSE

suppressWarnings(suppressMessages(library(tidymodels)))
library(BayesPharma)
library(drc)

bayesplot::bayesplot_theme_set(
  new = ggplot2::theme_bw())
```

{{< include BayesPharma_manuscript_sections/case_study_hill.qmd >}}
