---
title: "Apply: MuSyC Model -- KCNQ Conductance"
description: Demonstrate the MuSyC_model to analyze the interaction between
  voltage and small molecules interact modulate conductance through the KCNQ2
  voltage gated potassium channel.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Apply: MuSyC Model -- KCNQ Conductance}
  %\VignetteEncoding{UTF-8}
---

```{r set-options, echo=FALSE}

# inspired by
# https://www.jumpingrivers.com/blog/knitr-default-options-settings-hooks/
knitr::opts_chunk$set(
  cache = TRUE,
  echo = FALSE,
  fig.path = "apply_MuSyC_KCNQ_files/",
  fig.retina = 2, # Control using dpi
  fig.width = 6,  # generated images
  fig.height = 5, # generated images
  fig.pos = "t",  # pdf mode
  fig.align = "center",
  dpi = if (knitr::is_latex_output()) 72 else 300, 
  out.width = "100%")

```


```{r load-packages}
#| echo=FALSE
suppressWarnings(suppressMessages(library(tidyverse)))
library(BayesPharma)
```


```{r load-data}
#| echo=TRUE,
#| results='hide',
#| message=FALSE,

read_range <- function(
    sheet,
    range,
    treatment,
    dose_uM,
    is_control){
  readxl::read_excel(
    path = here::here(
      "inst", "extdata", "conductance_KCNQ", "Li_CellRes_2021_fig1.xlsx"),
    sheet = {{sheet}},
    range = range,
    col_names = FALSE,
    .name_repair = ~ paste0("replica_", 1:length(.))) |>
    dplyr::mutate(
      treatment = {{treatment}},
      dose_uM = {{dose_uM}},
      is_control = {{is_control}},
      voltage = seq(-90, 60, by = 10),
      .before = 1) |>
    tidyr::pivot_longer(
      cols = c(-treatment, -dose_uM, -is_control, -voltage),
      names_to = "replica",
      values_to = "conductance")
}

data <- dplyr::bind_rows(
  read_range(
    sheet = "fig1b", range = "E3:I18",
    treatment = "ztz240", dose_uM = 10, is_control = TRUE),
  read_range(
    sheet = "fig1b", range = "L3:P18",
    treatment = "ztz240", dose_uM = 10, is_control = FALSE),
  read_range(
    sheet = "fig1b", range = "E22:I37",
    treatment = "ztz240", dose_uM = 5, is_control = TRUE),
  read_range(
    sheet = "fig1b", range = "L22:P37",
    treatment = "ztz240", dose_uM = 5, is_control = FALSE),  
  read_range(
    sheet = "fig1b", range = "E40:I55",
    treatment = "ztz240", dose_uM = 3, is_control = TRUE),
  read_range(
    sheet = "fig1b", range = "L40:P55",
    treatment = "ztz240", dose_uM = 3, is_control = FALSE), 
  read_range(
    sheet = "fig1b", range = "E58:J73",
    treatment = "ztz240", dose_uM = 1, is_control = TRUE),
  read_range(
    sheet = "fig1b", range = "L58:Q73",
    treatment = "ztz240", dose_uM = 1, is_control = FALSE),   
  read_range(
    sheet = "fig1b", range = "E77:I92",
    treatment = "ztz240", dose_uM = 0.1, is_control = TRUE),
  read_range(
    sheet = "fig1b", range = "L77:P92",
    treatment = "ztz240", dose_uM = 0.1, is_control = FALSE),

  read_range(
    sheet = "fig 1d", range = "D2:I17",
    treatment = "retigabine", dose_uM = 30, is_control = TRUE),
  read_range(
    sheet = "fig 1d", range = "M2:R17",
    treatment = "retigabine", dose_uM = 30, is_control = FALSE),
  read_range(
    sheet = "fig 1d", range = "D20:I35",
    treatment = "retigabine", dose_uM = 10, is_control = TRUE),
  read_range(
    sheet = "fig 1d", range = "M20:R35",
    treatment = "retigabine", dose_uM = 10, is_control = FALSE),  
  read_range(
    sheet = "fig 1d", range = "D39:H54",
    treatment = "retigabine", dose_uM = 5, is_control = TRUE),
  read_range(
    sheet = "fig 1d", range = "M39:Q54",
    treatment = "retigabine", dose_uM = 5, is_control = FALSE), 
  read_range(
    sheet = "fig 1d", range = "D57:H72",
    treatment = "retigabine", dose_uM = 3, is_control = TRUE),
  read_range(
    sheet = "fig 1d", range = "M57:Q72",
    treatment = "retigabine", dose_uM = 3, is_control = FALSE),   
  read_range(
    sheet = "fig 1d", range = "D76:H91",
    treatment = "retigabine", dose_uM = 1, is_control = TRUE),
  read_range(
    sheet = "fig 1d", range = "M76:Q91",
    treatment = "retigabine", dose_uM = 1, is_control = FALSE),
  read_range(
    sheet = "fig 1d", range = "D95:H110",
    treatment = "retigabine", dose_uM = 0.3, is_control = TRUE),
  read_range(
    sheet = "fig 1d", range = "M95:Q110",
    treatment = "retigabine", dose_uM = 0.3, is_control = FALSE))
    
```


```{r prepare-model-data}
#| echo=FALSE
model_data <- data |>
  dplyr::filter(
    is_control == FALSE) |>
  dplyr::transmute(
    conductance,
    voltage = voltage/100,
    treatment = treatment,
    doselabel = paste(dose_uM, "uM") |> as.factor(),
    logdose = log10(dose_uM) - 6)

```


```{r plot-checkerboard}
plot_data <- data |>
  dplyr::filter(
    treatment == "ztz240",
    is_control == FALSE) |>
  dplyr::transmute(
    response = conductance,
    dose1 = dose_uM,
    dose2 = 10^(voltage))

BayesPharma::plot_synergy_checkerboard(
  data = plot_data,
  treatment_1_label = "ztz240",
  treatment_1_units = "μM",
  treatment_2_label = "Voltage",
  treatment_2_units = "mV") +
  ggplot2::coord_cartesian(default = TRUE) +
  ggplot2::scale_y_continuous(
    "Voltage (mV)",
    breaks = data$voltage |> unique() |> sort(),
    labels = signif(d2_label, 3),
      expand = c(0, 0))
```



```{r fit-model-conductance}
#| echo=TRUE,
#| results='hide',
#| message=FALSE,
#| dependson=c("prepare-model-data")

model_conductance <- BayesPharma::sigmoid_model(
  data = model_data,
  formula = BayesPharma::sigmoid_agonist_formula(
    treatment_variable = "voltage",
    treatment_units = "mV",
    response_variable = "conductance",
    response_units = "% Gmax",
    predictors = 0 + treatment:doselabel),
  prior = BayesPharma::sigmoid_agonist_prior(
    ec50 = brms::prior(normal(-0.2, 1), nlpar = "ec50"),
    hill = brms::prior(normal(3, 2), nlpar = "hill", lb = 1)),
  cores = 4)
```

```{r model-conductance-prior-posterior}
#| echo=TRUE,
#| message=FALSE,
#| dependson=c("model-conductance-by-voltage")

model_conductance |>
  BayesPharma::plot_prior_posterior_densities()
```

```{r model-conductance-predictive}
#| echo=TRUE,
#| message=FALSE,
#| dependson=c("model-conductance-by-voltage")

model_conductance |>
  BayesPharma::plot_posterior_draws()
```
Fit MuSyC Model

```{r fit-MuSyC-model}
#| echo=FALSE,
#| message=FALSE,
#| dependson=c("prepare-model-data")
model_MuSyC_meanfield <- BayesPharma::MuSyC_model(
  data = model_data,
  formula = BayesPharma::MuSyC_formula(
    treatment_1_variable = "voltage",
    treatment_2_variable = "log_dose",
    response_variable = "conductance"),
  algorithm = "meanfield")

model_MuSyC <- BayesPharma::MuSyC_model(
  data = model_data,
  formula = BayesPharma::MuSyC_formula(
    treatment_1_variable = "voltage",
    treatment_2_variable = "logdose",
    response_variable = "conductance"),
  prior = BayesPharma::MuSyC_prior(
    logE0 = log(0),
    logE1 = log(1),
    logC1 = brms::prior(normal(-0.2, 1), nlpar = "logC1"),
    h1 = brms::prior(normal(1, 1), nlpar = "h1"),
    logE2 = log(0),
    logC2 = brms::prior(normal(-6, 2), nlpar = "logC2"),
    h2 = brms::prior(normal(-1, 1), nlpar = "h2"),    
    logE3 = log(1),
    logalpha = brms::prior(normal(0, 1), nlpar = "logalpha")),
  control = list(
      adapt_delta = .99,
      max_treedepth = 12),
  stanvars = BayesPharma::MuSyC_stanvar(),
  cores = 4)
```

Join the conductance model with the dose information to model how the voltage
dependence depends on the drug dose
```{r extract-voltage-by-dose}
#| echo=FALSE,
#| message=FALSE,
#| dependson=c("prepare-model-data", "model-conductance-by-voltage")

data_conductance_by_voltage <- model_conductance |>
  posterior::summarize_draws() |>
  tidyr::separate_wider_delim(
    cols = variable,
    delim = "_",
    names = c("variable_type", "variable", "predictors_label"),
    too_few = "align_start") |>
  dplyr::filter(variable_type == "b") |>
  dplyr::inner_join(
    model_data |>
      dplyr::distinct(treatment, logdose, doselabel) |>
      dplyr::mutate(
        predictors_label = paste0(
          "treatment", treatment, ":",
          "doselabel", doselabel |> stringr::str_replace(" ", ""))),
    by = "predictors_label")
data_conductance_by_voltage

```


```{r plot-voltage-by-dose}
#| echo=FALSE,
#| message=FALSE,
#| dependson=c("extract-voltage-by-dose")
plot <- ggplot2::ggplot(
  data = data_conductance_by_voltage) +
  ggplot2::theme_bw() +
  ggplot2::geom_ribbon(
    mapping = ggplot2::aes(
      x = logdose,
      ymin = q5,
      ymax = q95,
      fill = treatment),
    alpha = .2) +
  ggplot2::geom_line(
    mapping = ggplot2::aes(
      x = logdose,
      y = mean,
      color = treatment),
    linewidth = 1.8) +
  ggplot2::facet_wrap(
    facets = dplyr::vars(variable),
    scales = "free_y") +
  ggplot2::theme(legend.position = "bottom") +
  ggplot2::scale_color_viridis_d("Treatment", begin=.2, end=0.8) +
  ggplot2::scale_fill_viridis_d("Treatment", begin=0.2, end=0.8) +
  ggplot2::scale_x_continuous("Log[Molar]") +
  ggplot2::scale_y_continuous("Parameter Value")
plot
```

```{r fit-bilevel-model}
#| echo=FALSE,
#| message=FALSE,
#| dependson=c("extract-voltage-by-dose")
model_bilevel <- brms::brm(
  data = model_data,
  formula = brms::brmsformula(
    conductance ~ sigmoid(
      sigmoid(Eec50, Ehill, Etop, Ebottom, logdose),
      sigmoid(Hec50, Hhill, Htop, Hbottom, logdose),
      vtop,
      vbottom,
      voltage),
    vtop + vbottom ~ 1,
    Eec50 + Ehill + Etop + Ebottom ~ 0 + treatment,
    Hec50 + Hhill + Htop + Hbottom ~ 0 + treatment,
    nl = TRUE),
  prior = c(
    brms::prior(prior = normal(-6, 2.5), nlpar = "Eec50"),
    brms::prior(prior = normal(-1.5, 1), nlpar = "Ehill", ub = 0.01),
    brms::prior(prior = normal(-.1, 0.05), nlpar = "Etop"),
    brms::prior(prior = normal(-.4, 0.05), nlpar = "Ebottom"),
    
    brms::prior(prior = normal(-6, 2.5), nlpar = "Hec50"),
    brms::prior(prior = normal(1, 1), nlpar = "Hhill", lb = 0.01),
    brms::prior(prior = normal(5, 2), nlpar = "Htop"),
    brms::prior(prior = normal(3, 0.1), nlpar = "Hbottom"),    
    
    brms::prior(prior = normal(1, 0.3), nlpar = "vtop"),
    brms::prior(prior = normal(0, 0.3), nlpar = "vbottom")),
  control = list(
      adapt_delta = .99,
      max_treedepth = 12),
  stanvars = BayesPharma::sigmoid_stanvar(),
  cores = 4)
```


```{r summarize-bilevel-model}
#| echo=FALSE,
#| message=FALSE,
#| dependson=c("fit-bilevel-model")
model_bilevel
```




```{r compare-model-fits}
#| echo=FALSE,
#| message=FALSE,
#| dependson=c("fit-MuSyC-model", "fit-bilevel-model")
brms::loo_compare(model_MuSyC, model_bilevel)
```

