---
# For vignette -----------------------------------------------------------------
title: "Apply: Sigmoid Model -- KOR Antagonists"
subtitle: Analysis of Four Kappa Opioid Receptor Antagonists
description: Demonstrate the applying a sigmoid model electrophysiology data
# Document ---------------------------------------------------------------------
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Apply: Sigmoid Model -- KOR Antagonists}
  %\VignetteKeyword{BayesPharma}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{drc}

---

```{r set-options}
#| echo=FALSE
options(rmarkdown.html_vignette.check_title = FALSE)

# inspired by https://www.jumpingrivers.com/blog/knitr-default-options-settings-hooks/
knitr::opts_chunk$set(
  cache = TRUE,
  echo = FALSE,
  fig.path = here::here(
    "vignettes", "apply_sigmoid_model_KOR_antagonists_files/"),
  fig.retina = 2, # Control using dpi
  fig.width = 6,  # generated images
  fig.height = 5, # generated images
  fig.pos = "t",  # pdf mode
  fig.align = "center",
  dpi = if (knitr::is_latex_output()) 72 else 300, 
  out.width = "100%",
  collapse = TRUE)

set.seed(0)
```

```{r load-packages}
#| echo=FALSE

suppressWarnings(suppressMessages(library(tidymodels)))
library(BayesPharma)
library(drc)

bayesplot::bayesplot_theme_set(
  new = ggplot2::theme_bw())
```

```{r}
#| child = here::here("vignettes_src", "manuscript", "sections", "case_study_hill.qmd")

```

