---
title: "Apply: tQ Model -- ChABC Design"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Apply: tQ Model -- ChABC Design}
  %\VignetteEncoding{UTF-8}
---
  
```{r set-options}
#| echo=FALSE

# inspired by https://www.jumpingrivers.com/blog/knitr-default-options-settings-hooks/
knitr::opts_chunk$set(
  cache = TRUE,
  echo = FALSE,
  fig.path = here::here("vignettes", "apply_model_tQ_ChABC_design_files/"),
  fig.retina = 2, # Control using dpi
  fig.width = 6,  # generated images
  fig.height = 5, # generated images
  fig.pos = "t",  # pdf mode
  fig.align = "center",
  dpi = if (knitr::is_latex_output()) 72 else 300, 
  out.width = "100%")
```


```{r load-packages}
suppressWarnings(suppressMessages(library(tidyverse)))
library(BayesPharma)
library(GeomIndicator)
suppressWarnings(suppressMessages(library(tidybayes)))
```


```{r read-data}
#| echo=FALSE
data_path <- here::here(
  "inst", "extdata", "enzyme_kinetics", "Hettiaratchi_2020.xlsx")

data <- tibble::tibble(
  sheet_name = readxl::excel_sheets(data_path)[2:7]) |>
  dplyr::rowwise() |>
  dplyr::do({
    sheet_name <- .$sheet_name
    data <- readxl::read_excel(
      path = data_path,
      sheet = sheet_name,
      range = "R2C2:R65C18",
      col_names = TRUE,
      .name_repair = ~ paste0("column_", 1:length(.))) |>
      dplyr::mutate(
        substrate_concentration_mg_ml = sheet_name |>
          stringr::str_extract("^[0-9.]+") |>
          as.numeric(),
          .before = 1)
  }) |>
  dplyr::ungroup()
names(data)[seq(4, 16, by = 3)] <- paste0(
  data[1,2:16] |> as.character() |> na.omit(), "_1")
names(data)[seq(5, 17, by = 3)] <- paste0(
  data[1,2:16] |> as.character() |> na.omit(), "_2")
names(data)[seq(6, 18, by = 3)] <- paste0(
  data[1,2:16] |> as.character() |> na.omit(), "_3")
names(data)[2] <- "time_s"
names(data)[3] <- "temperature_C"
data <- data |>
  dplyr::filter(
    !is.na(time_s),
    time_s != "Time [s]") |>
  tidyr::pivot_longer(
    cols = -c("substrate_concentration_mg_ml", "time_s", "temperature_C"),
    names_to = "treatment_replica",
    values_to = "product_concentration") |>
  tidyr::separate(
    col = treatment_replica,
    into = c("treatment", "replica"),
    sep = "_") |>
  dplyr::mutate(
    replica = as.factor(replica),
    time_s = as.numeric(time_s),
    temperature_C = as.numeric(temperature_C),
    product_concentration = dplyr::case_when(
      product_concentration == "OVER" ~ NA_real_,
      TRUE ~ as.numeric(product_concentration)))

baseline <- data |>
  dplyr::filter(treatment == "Blank") |>
  dplyr::group_by(substrate_concentration_mg_ml, time_s) |>
  dplyr::summarize(
    mean_baseline = mean(product_concentration, na.rm=TRUE),
    .groups = "drop")

data <- data |>
  dplyr::left_join(
    baseline,
    by = c("substrate_concentration_mg_ml", "time_s")) |>
  dplyr::mutate(
    normalized_product_concentration = product_concentration - mean_baseline)

```


```{r plot-data}
ggplot2::ggplot(data = data |> dplyr::filter(treatment != "Blank")) + 
  ggplot2::theme_bw() +
  ggplot2::geom_line(
    mapping = ggplot2::aes(
      x = time_s,
      y = product_concentration * 0.93,
      color = log(substrate_concentration_mg_ml),
      group = paste0(substrate_concentration_mg_ml, "_", replica))) +
  ggplot2::geom_smooth(
    data = data |>
      dplyr::filter(
        treatment != "Blank",
        time_s <= 200),
    mapping = ggplot2::aes(
      x = time_s,
      y = product_concentration * 0.7,
      group = paste0(substrate_concentration_mg_ml, "_", replica)),
    method = "lm",
    formula = y ~ x,
    color = "orange") +
  ggplot2::facet_wrap(
    facets = dplyr::vars(treatment),
    nrow = 1) +
  ggplot2::theme(legend.position = "bottom") +
  ggplot2::scale_color_continuous(
    "Substrate mg/ml:",
    breaks = log(c(0.5, 1, 2.5, 5, 10, 15)),
    labels = c("0.5", "1", "2.5", "5", "10", "15")) +
  ggplot2::scale_x_continuous("Time (s)") +
  ggplot2::scale_y_continuous(
    "Product mg/ml:",
    breaks = c(0.5, 1, 2.5, 5, 10, 15),
    labels = c("0.5", "1", "2.5", "5", "10", "15")) 

```
```{r simulate-tQ}
data_simulate <- tidyr::expand_grid(
  kcat = 0.0072,
  kM =  0.0448,
  ET = 1,
  ST = c(0.5, 1, 2.5, 5, 10, 15)) |>
  dplyr::mutate(series_index = dplyr::row_number()) |>
  dplyr::rowwise() |>
  dplyr::do({
    data <- .
    time <- seq(0, 1200, by=20)
    data <- data.frame(data,
      time = time,
      P = BayesPharma::tQ_model_generate(
        time = time,
        kcat = data$kcat,
        kM = data$kM,
        ET = data$ET,
        ST = data$ST)[,2])
  })

ggplot2::ggplot(data = data_simulate) + 
  ggplot2::theme_bw() +
  ggplot2::geom_line(
    mapping = ggplot2::aes(
      x = time,
      y = 0.8 + 0.16*P,
      color = log(ST),
      group = ST)) +
  ggplot2::theme(legend.position = "bottom") +
  ggplot2::scale_color_continuous(
    "Substrate mg/ml:",
    breaks = log(c(0.5, 1, 2.5, 5, 10, 15)),
    labels = c("0.5", "1", "2.5", "5", "10", "15")) +
  ggplot2::scale_x_continuous("Time (s)") +
  ggplot2::scale_y_continuous(
    "Product mg/ml:",
    breaks = c(0.5, 1, 2.5, 5, 10, 15),
    labels = c("0.5", "1", "2.5", "5", "10", "15"))



```

```{r model-tQ}
z <- data |>
  dplyr::filter(treatment |> stringr::str_detect("^D")) |>
  dplyr::arrange(
    treatment,
    substrate_concentration_mg_ml,
    replica,
    time_s)

z <- z |>
  dplyr::left_join(
    z |>
      dplyr::distinct(
        treatment,
        substrate_concentration_mg_ml,
        replica) |>
      dplyr::mutate(
        series_index = dplyr::row_number()),
    by = c("treatment", "substrate_concentration_mg_ml", "replica")) |>
  dplyr::filter(time_s > 0) |>
  dplyr::filter(!is.na(normalized_product_concentration)) |>
  dplyr::transmute(
    series_index,
    treatment,
    ET = 1,
    ST = substrate_concentration_mg_ml,
    P = product_concentration,
    time = time_s)

# model <- brms::brm(
#     data = z,
#     formula = brms::brmsformula(
#       P ~ baseline + scale * prod,
#       brms::nlf(
#         prod ~ tQ_multiple(series_index, time, kcat, kM, ET, ST),
#         loop = FALSE),
#       kcat + kM ~ 0 + treatment,
#       baseline + scale ~ 1,
#       nl = TRUE),
#     prior = c(
#       brms::prior(prior = gamma(0.25, 0.01), lb = 0, nlpar = "kcat"),
#       brms::prior(prior = gamma(6, 0.01), lb = 0, nlpar = "kM"),
#       brms::prior(prior = normal(0, 3), nlpar = "baseline"),
#       brms::prior(prior = normal(1, 3), nlpar = "scale")),
#     init = function() list(
#       kcat = 250,
#       kM = 6000,
#       baseline = 0,
#       scale = 1),
#     iter = 4000,
#     cores = 4,
#     seed = 52L,
#     backend = 'cmdstanr',
#     stanvars = BayesPharma::tQ_stanvar,
#     algorithm = "meanfield")


model <- BayesPharma::tQ_model(
    data = z |>
      dplyr::filter(treatment == "D14-14"),
    #formula = tQ_formula(),
    #prior = tQ_prior(
    #  kcat = brms::prior(prior = gamma(2, 1), lb = 0, nlpar = "kcat"),
    #  kM = brms::prior(prior = gamma(1000, 1), lb = 0, nlpar = "kM")),
    formula = brms::brmsformula(
      P ~ tQ_multiple(series_index, time, kcat, 10^logkM, ET, ST),
      kcat ~ 1,
      logkM ~ 1,
      nl = TRUE,
      loop = FALSE),
    prior = c(
        brms::prior(prior = gamma(2, 10), lb = 0, nlpar = "kcat"),
        brms::prior(prior = normal(2, 1), nlpar = "logkM")),
    init = function() list(b_kcat = 0.2, b_logkM = 2),
    iter = 8000,
    control = NULL,
    algorithm = "meanfield")
```


```{r model-multiple-draws, deps=c("model-multiple", "model-multiple-prior")}
model_prior <- model |>
  update(sample_prior = "only")

draws_prior <- model_prior |>
  tidybayes::tidy_draws() |>
  tidybayes::gather_variables() |>
  dplyr::filter(.variable |> stringr::str_detect("b_(kcat|logkM)")) |>
  tidyr::separate(.variable, into = c("class", "parameter", "treatment"), sep = "_") |>
  dplyr::mutate(treatment = treatment |> stringr::str_replace("treatment", ""))

draws_posterior <- model |>
  tidybayes::tidy_draws() |>
  tidybayes::gather_variables() |>
  dplyr::filter(.variable |> stringr::str_detect("b_(kcat|logkM)")) |>
  tidyr::separate(.variable, into = c("class", "parameter", "treatment"), sep = "_") |>
  dplyr::mutate(treatment = treatment |> stringr::str_replace("treatment", ""))
```

```{r prior-posterior-multiple-scatter, deps=c("model-multiple-draws")}
draws_prior_pairs <- draws_prior |>
  tidyr::pivot_wider(
    id_cols = c(".chain", ".iteration", ".draw", "treatment"),
    names_from = "parameter",
    values_from = ".value")

draws_posterior_pairs <- draws_posterior |>
  tidyr::pivot_wider(
    id_cols = c(".chain", ".iteration", ".draw", "treatment"),
    names_from = "parameter",
    values_from = ".value")

ggplot2::ggplot() +
  ggplot2::theme_bw() +
    ggplot2::geom_point(
    data = draws_prior_pairs,
    mapping = ggplot2::aes(
      x = log10(kcat),
      y = logkM),
    color = "orange",
    size = .8,
    shape = 16,
    alpha = .3) +  
    ggplot2::geom_point(
    data = draws_posterior_pairs,
    mapping = ggplot2::aes(
      x = log10(kcat),
      y = logkM),
    color = "blue",
    size = .8,
    shape = 16,
    alpha = .3) +
  ggplot2::scale_x_continuous("catalytic constant log(kcat)") +
  ggplot2::scale_y_continuous("Michaelis constant log(kM)") +
  ggplot2::facet_wrap(facets = dplyr::vars(treatment), nrow = 1, scales = "free")
```

